---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  finalizers: []
  labels:
    app: "order-data-service"
  name: "order-data-service-service"
  namespace: "default"
  ownerReferences: []
spec:
  externalIPs: []
  loadBalancerSourceRanges: []
  ports:
  - port: 8280
    name: http
  - port: 9797
    name: prometheus                 
  selector:
    app: "order-data-service"
  type: "LoadBalancer"
