---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations: {}
  finalizers: []
  labels:
    app: "order-outbound-dispatcher"
  name: "order-outbound-dispatcher-deployment"
  namespace: "default"
  ownerReferences: []
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "9797"
      finalizers: []
      labels:
        app: "order-outbound-dispatcher"
      ownerReferences: []
    spec:
      containers:
      - args: []
        command: []
        env:
          - name: order_mb_host
            value: "b7a-mb-service.default.svc.cluster.local"
          - name: order_mb_port
            value: "5672"
          - name: b7a_observability_tracing_jaeger_reporter_hostname
            value: "jaeger-udp-service.default.svc.cluster.local"  
          - name: order_data_service_url
            value: "http://order-data-service-service.default.svc.cluster.local:8280/data/order"                                   
        envFrom: []
        image: "rajkumar/order-outbound-dispatcher:0.1.1"
        imagePullPolicy: "IfNotPresent"
        name: "order-outbound-dispatcher-deployment"
        ports:       
        - containerPort: 8280
          name: http 
        - containerPort: 9797
          name: prometheus           
        volumeMounts: []
      hostAliases: []
      imagePullSecrets: []
      initContainers: []
      nodeSelector: {}
      tolerations: []
      volumes: []
